"""Public contracts for residual Source/Retrieval/Evidence/Diagnostics responsibilities."""

from odoo_ai.contracts.agent import (
    AnswerConfidence,
    AnswerEnvelope,
    ProposedAction,
    ToolRisk,
    ToolSpec,
)
from odoo_ai.contracts.content_source import ContentSourceDescriptor, Fingerprint
from odoo_ai.contracts.context import (
    ContextPack,
    ConversationState,
    InstanceProfileSummary,
    TurnLimits,
    UserExecutionContext,
    UserRequest,
    Workflow,
)
from odoo_ai.contracts.diagnostics import (
    EmptyDiagnosticsRequest,
    LogTestDiagnostics,
    SourceScanDiagnostics,
    SourceStatusDiagnostics,
    SourceTestDiagnostics,
    TracebackRequest,
)
from odoo_ai.contracts.evidence import (
    Evidence,
    EvidenceKind,
    EvidenceSensitivity,
    EvidenceStatus,
)
from odoo_ai.contracts.knowledge import (
    KnowledgeChunk,
    KnowledgeDocument,
    KnowledgeDocumentStatus,
    KnowledgeExcerpt,
    KnowledgeExcerptLine,
    KnowledgeMediaType,
    KnowledgeProviderIssue,
    KnowledgeProviderResult,
    KnowledgeReadExcerptRequest,
    KnowledgeRef,
    KnowledgeScanMetrics,
    KnowledgeScanResult,
    KnowledgeSearchCandidate,
    KnowledgeSearchRequest,
    KnowledgeSearchResult,
    KnowledgeStoredChunk,
)
from odoo_ai.contracts.logs import (
    LogCorrelation,
    LogEvidence,
    LogSearchRequest,
    TimestampRange,
)
from odoo_ai.contracts.records import RecordRef, RecordSnapshot
from odoo_ai.contracts.schema import JsonSchema, export_public_json_schemas
from odoo_ai.contracts.screen_context import ScreenContext
from odoo_ai.contracts.source import (
    FindModelExtensionsRequest,
    FindModelExtensionsResult,
    FindSymbolRequest,
    FindSymbolResult,
    InstanceInventory,
    ManifestMetadata,
    ModelExtensionGroup,
    ReadExcerptRequest,
    ScanRun,
    SourceCandidate,
    SourceExcerpt,
    SourceExcerptLine,
    SourceFile,
    SourceRef,
    SourceSymbol,
    XmlRecord,
)
from odoo_ai.contracts.tool_execution import ToolExecutionEvent, ToolExecutionReport

__all__ = [
    "AnswerConfidence",
    "AnswerEnvelope",
    "ContentSourceDescriptor",
    "ContextPack",
    "ConversationState",
    "EmptyDiagnosticsRequest",
    "Evidence",
    "EvidenceKind",
    "EvidenceSensitivity",
    "EvidenceStatus",
    "FindModelExtensionsRequest",
    "FindModelExtensionsResult",
    "FindSymbolRequest",
    "FindSymbolResult",
    "Fingerprint",
    "InstanceInventory",
    "InstanceProfileSummary",
    "JsonSchema",
    "KnowledgeChunk",
    "KnowledgeDocument",
    "KnowledgeDocumentStatus",
    "KnowledgeExcerpt",
    "KnowledgeExcerptLine",
    "KnowledgeMediaType",
    "KnowledgeProviderIssue",
    "KnowledgeProviderResult",
    "KnowledgeReadExcerptRequest",
    "KnowledgeRef",
    "KnowledgeScanMetrics",
    "KnowledgeScanResult",
    "KnowledgeSearchCandidate",
    "KnowledgeSearchRequest",
    "KnowledgeSearchResult",
    "KnowledgeStoredChunk",
    "LogCorrelation",
    "LogEvidence",
    "LogSearchRequest",
    "LogTestDiagnostics",
    "ManifestMetadata",
    "ModelExtensionGroup",
    "ProposedAction",
    "ReadExcerptRequest",
    "RecordRef",
    "RecordSnapshot",
    "ScanRun",
    "ScreenContext",
    "SourceCandidate",
    "SourceExcerpt",
    "SourceExcerptLine",
    "SourceFile",
    "SourceRef",
    "SourceScanDiagnostics",
    "SourceStatusDiagnostics",
    "SourceSymbol",
    "SourceTestDiagnostics",
    "TimestampRange",
    "ToolExecutionEvent",
    "ToolExecutionReport",
    "ToolRisk",
    "ToolSpec",
    "TracebackRequest",
    "TurnLimits",
    "UserExecutionContext",
    "UserRequest",
    "Workflow",
    "XmlRecord",
    "export_public_json_schemas",
]
