"""Stable, transport-independent contracts for the Assistant Service."""

from odoo_ai.contracts.agent import (
    AnswerConfidence,
    AnswerEnvelope,
    ProposedAction,
    ToolRisk,
    ToolSpec,
)
from odoo_ai.contracts.context import (
    ContextPack,
    ConversationState,
    InstanceProfileSummary,
    TurnLimits,
    UserExecutionContext,
    UserRequest,
    Workflow,
)
from odoo_ai.contracts.delegation import (
    DELEGATION_FORMAT_VERSION,
    ContextReadTurnRequest,
    ContextReadTurnResponse,
    DelegationClaims,
    DelegationScope,
    OdooGatewayReference,
)
from odoo_ai.contracts.evidence import (
    Evidence,
    EvidenceKind,
    EvidenceSensitivity,
    EvidenceStatus,
)
from odoo_ai.contracts.logs import (
    LogCorrelation,
    LogEvidence,
    LogSearchRequest,
    TimestampRange,
)
from odoo_ai.contracts.records import RecordRef, RecordSnapshot
from odoo_ai.contracts.schema import PUBLIC_CONTRACT_MODELS, export_public_json_schemas
from odoo_ai.contracts.screen_context import ScreenContext
from odoo_ai.contracts.source import (
    FindModelExtensionsRequest,
    FindModelExtensionsResult,
    FindSymbolRequest,
    FindSymbolResult,
    InstanceInventory,
    ManifestMetadata,
    ManifestStatus,
    ModelExtensionGroup,
    ReadExcerptRequest,
    ScanRun,
    ScanStatus,
    SourceCandidate,
    SourceCapabilityState,
    SourceExcerpt,
    SourceExcerptLine,
    SourceFile,
    SourceFileKind,
    SourceMatchReason,
    SourceProvenance,
    SourceRef,
    SourceSymbol,
    XmlRecord,
)

__all__ = [
    "AnswerConfidence",
    "AnswerEnvelope",
    "ContextPack",
    "ConversationState",
    "ContextReadTurnRequest",
    "ContextReadTurnResponse",
    "DELEGATION_FORMAT_VERSION",
    "DelegationClaims",
    "DelegationScope",
    "Evidence",
    "EvidenceKind",
    "EvidenceSensitivity",
    "EvidenceStatus",
    "FindModelExtensionsRequest",
    "FindModelExtensionsResult",
    "FindSymbolRequest",
    "FindSymbolResult",
    "InstanceInventory",
    "InstanceProfileSummary",
    "LogCorrelation",
    "LogEvidence",
    "LogSearchRequest",
    "ManifestMetadata",
    "ManifestStatus",
    "ModelExtensionGroup",
    "OdooGatewayReference",
    "ProposedAction",
    "PUBLIC_CONTRACT_MODELS",
    "RecordRef",
    "RecordSnapshot",
    "ReadExcerptRequest",
    "ScanRun",
    "ScanStatus",
    "ScreenContext",
    "SourceCapabilityState",
    "SourceCandidate",
    "SourceExcerpt",
    "SourceExcerptLine",
    "SourceFile",
    "SourceFileKind",
    "SourceMatchReason",
    "SourceProvenance",
    "SourceRef",
    "SourceSymbol",
    "ToolRisk",
    "ToolSpec",
    "TimestampRange",
    "TurnLimits",
    "UserExecutionContext",
    "UserRequest",
    "Workflow",
    "XmlRecord",
    "export_public_json_schemas",
]
