"""Addon-local extension framework for agent capabilities.

Core provider modules remain automatically discovered. Trusted installed Odoo addons may
also contribute :class:`CapabilityProvider` markers; every executable operation still
resolves to the same host-owned :class:`CapabilityDefinition` contract.
"""

from .attachment_evidence import build_turn_attachment_evidence_provider
from .config import CapabilityConfigResolver
from .context import (
    ContextCollector,
    ContextContribution,
    ContextProvider,
    ContextProviderCatalog,
    ContextProviderStatus,
)
from .contracts import (
    CapabilityActivityProjector,
    CapabilityActivitySpec,
    CapabilityApproval,
    CapabilityContext,
    CapabilityDefinition,
    CapabilityDependency,
    CapabilityEffect,
    CapabilityError,
    CapabilityExposure,
    CapabilityPreview,
    CapabilityResult,
    CapabilityRisk,
    CapabilitySetting,
    CapabilitySettingType,
    CapabilityVerification,
    FrozenDict,
    FrozenList,
    JsonValue,
    freeze_contract_json,
    freeze_contract_mapping,
    thaw_contract_json,
)
from .decorators import tool
from .disclosure import (
    CapabilityDisclosureSnapshot,
    DisclosurePolicy,
    build_disclosure_snapshot,
)
from .evidence import (
    EvidenceAccessScope,
    EvidenceFreshness,
    EvidenceItem,
    EvidenceKind,
    EvidenceLedger,
    EvidenceLedgerSnapshot,
    EvidenceLocator,
    EvidenceProvider,
    EvidenceProviderCatalog,
    EvidenceProviderStatus,
    EvidenceRef,
    EvidenceRoutingPolicy,
    EvidenceSearchBatch,
    EvidenceSearchRequest,
    EvidenceSearchResult,
    EvidenceTrust,
    canonical_fingerprint,
    canonical_json_bytes,
    freeze_json,
    freeze_json_mapping,
    redact_secrets,
    thaw_json,
)
from .evidence_runtime import (
    AssistantEvidenceDecisionEngine,
    EvidenceFetchFailure,
    EvidenceWorkingContext,
)
from .executor import CapabilityExecutor
from .extensions import (
    ActiveAssistantExtensions,
    AssistantExtensionCatalog,
    AssistantExtensionStatus,
    compose_assistant_extensions,
    discover_assistant_extensions_for_env,
)
from .features import (
    ProviderFeature,
    ProviderFeatureState,
    ProviderFeatureSupport,
    ProviderProfile,
)
from .log_evidence import build_odoo_log_evidence_provider
from .manifest import (
    EffectiveAssistantManifest,
    TechnicalAccessProfile,
    build_effective_assistant_manifest,
    technical_access_profile_for_env,
)
from .policy import CapabilityPolicy, CapabilityPolicyDecision, ExecutionAuthority
from .profiles import (
    ProductUserProfile,
    product_profile_for_env,
    product_profile_from_technical,
)
from .provider import (
    CAPABILITY_PROVIDER_API_VERSION,
    RESERVED_PROVIDER_NAMESPACES,
    CapabilityProvider,
    CapabilityProviderLoader,
    CapabilityProviderStatus,
    discover_odoo_capability_providers,
)
from .registry import (
    CapabilityRegistry,
    clear_discovery_cache,
    compose_capability_registry,
    discover_capabilities,
    discover_capabilities_for_env,
)
from .skills import SkillCatalog, SkillDefinition, selector_matches
from .source_evidence import build_installed_source_evidence_provider

__all__ = [
    "CAPABILITY_PROVIDER_API_VERSION",
    "RESERVED_PROVIDER_NAMESPACES",
    "ActiveAssistantExtensions",
    "AssistantEvidenceDecisionEngine",
    "AssistantExtensionCatalog",
    "AssistantExtensionStatus",
    "CapabilityActivityProjector",
    "CapabilityActivitySpec",
    "CapabilityApproval",
    "CapabilityConfigResolver",
    "CapabilityContext",
    "CapabilityDefinition",
    "CapabilityDependency",
    "CapabilityDisclosureSnapshot",
    "CapabilityEffect",
    "CapabilityError",
    "CapabilityExecutor",
    "CapabilityExposure",
    "CapabilityPolicy",
    "CapabilityPolicyDecision",
    "CapabilityPreview",
    "CapabilityProvider",
    "CapabilityProviderLoader",
    "CapabilityProviderStatus",
    "CapabilityRegistry",
    "CapabilityResult",
    "CapabilityRisk",
    "CapabilitySetting",
    "CapabilitySettingType",
    "CapabilityVerification",
    "ContextCollector",
    "ContextContribution",
    "ContextProvider",
    "ContextProviderCatalog",
    "ContextProviderStatus",
    "DisclosurePolicy",
    "EffectiveAssistantManifest",
    "EvidenceAccessScope",
    "EvidenceFetchFailure",
    "EvidenceFreshness",
    "EvidenceItem",
    "EvidenceKind",
    "EvidenceLedger",
    "EvidenceLedgerSnapshot",
    "EvidenceLocator",
    "EvidenceProvider",
    "EvidenceProviderCatalog",
    "EvidenceProviderStatus",
    "EvidenceRef",
    "EvidenceRoutingPolicy",
    "EvidenceSearchBatch",
    "EvidenceSearchRequest",
    "EvidenceSearchResult",
    "EvidenceTrust",
    "EvidenceWorkingContext",
    "ExecutionAuthority",
    "FrozenDict",
    "FrozenList",
    "JsonValue",
    "ProductUserProfile",
    "ProviderFeature",
    "ProviderFeatureState",
    "ProviderFeatureSupport",
    "ProviderProfile",
    "SkillCatalog",
    "SkillDefinition",
    "TechnicalAccessProfile",
    "build_disclosure_snapshot",
    "build_effective_assistant_manifest",
    "build_installed_source_evidence_provider",
    "build_odoo_log_evidence_provider",
    "build_turn_attachment_evidence_provider",
    "canonical_fingerprint",
    "canonical_json_bytes",
    "clear_discovery_cache",
    "compose_assistant_extensions",
    "compose_capability_registry",
    "discover_assistant_extensions_for_env",
    "discover_capabilities",
    "discover_capabilities_for_env",
    "discover_odoo_capability_providers",
    "freeze_contract_json",
    "freeze_contract_mapping",
    "freeze_json",
    "freeze_json_mapping",
    "product_profile_for_env",
    "product_profile_from_technical",
    "redact_secrets",
    "selector_matches",
    "technical_access_profile_for_env",
    "thaw_contract_json",
    "thaw_json",
    "tool",
]
