"""PostgreSQL persistence infrastructure for residual service responsibilities."""

from odoo_ai.storage.action_repository import ActionStoreError, SqlActionApprovalStore
from odoo_ai.storage.base import Base
from odoo_ai.storage.config import DatabaseConfigurationError, DatabaseSettings
from odoo_ai.storage.database import create_database_engine, create_session_factory, session_scope
from odoo_ai.storage.knowledge_repository import (
    KnowledgeDocumentUpsert,
    KnowledgeSearchRows,
    get_current_knowledge_chunk,
    get_knowledge_document,
    list_knowledge_chunks,
    retire_missing_knowledge_documents,
    search_current_knowledge_chunks,
    upsert_knowledge_document,
)
from odoo_ai.storage.models import (
    ActionAuditRecord,
    ActionProposalRecord,
    CapabilitySnapshot,
    InstanceProfile,
    KnowledgeChunk,
    KnowledgeDocument,
    ScanRun,
    SourceFile,
    SourceSymbol,
    TraceEvent,
    XmlRecord,
)
from odoo_ai.storage.runtime_repository import (
    UnsafeTraceAttributesError,
    create_capability_snapshot,
    create_instance_profile,
    create_trace_event,
    get_instance_profile,
    get_latest_capability_snapshot,
    get_latest_instance_profile,
    list_trace_events,
    record_log_capability,
    record_reasoning_capability,
    record_source_capability,
)
from odoo_ai.storage.source_repository import (
    IndexedSourcePointer,
    IndexedSourceSymbol,
    SourceFileUpsert,
    SourceSymbolValues,
    XmlRecordValues,
    delete_stale_source_files,
    find_indexed_model_extensions,
    find_source_symbols,
    find_unchanged_source_file_id,
    find_xml_records,
    finish_scan,
    get_indexed_source_pointer,
    get_latest_scan_run,
    mark_stale_source_files,
    open_scan,
    replace_file_derivatives,
    search_indexed_source_symbols,
    upsert_source_file,
)

__all__ = [
    "ActionAuditRecord",
    "ActionProposalRecord",
    "ActionStoreError",
    "Base",
    "CapabilitySnapshot",
    "DatabaseConfigurationError",
    "DatabaseSettings",
    "IndexedSourcePointer",
    "IndexedSourceSymbol",
    "InstanceProfile",
    "KnowledgeChunk",
    "KnowledgeDocument",
    "KnowledgeDocumentUpsert",
    "KnowledgeSearchRows",
    "ScanRun",
    "SourceFile",
    "SourceFileUpsert",
    "SourceSymbol",
    "SourceSymbolValues",
    "SqlActionApprovalStore",
    "TraceEvent",
    "UnsafeTraceAttributesError",
    "XmlRecord",
    "XmlRecordValues",
    "create_capability_snapshot",
    "create_database_engine",
    "create_instance_profile",
    "create_session_factory",
    "create_trace_event",
    "delete_stale_source_files",
    "find_indexed_model_extensions",
    "find_source_symbols",
    "find_unchanged_source_file_id",
    "find_xml_records",
    "finish_scan",
    "get_current_knowledge_chunk",
    "get_indexed_source_pointer",
    "get_instance_profile",
    "get_knowledge_document",
    "get_latest_capability_snapshot",
    "get_latest_instance_profile",
    "get_latest_scan_run",
    "list_knowledge_chunks",
    "list_trace_events",
    "mark_stale_source_files",
    "open_scan",
    "record_log_capability",
    "record_reasoning_capability",
    "record_source_capability",
    "replace_file_derivatives",
    "retire_missing_knowledge_documents",
    "search_current_knowledge_chunks",
    "search_indexed_source_symbols",
    "session_scope",
    "upsert_knowledge_document",
    "upsert_source_file",
]
