"""Replaceable infrastructure adapters for stable service ports."""

from odoo_ai.adapters.codex_engine import (
    CodexAppServerEngine,
    CodexEngineError,
    CodexEngineLimits,
    CodexEngineMetadata,
    codex_dynamic_tool_name,
    codex_dynamic_tools,
    serialize_codex_context,
)
from odoo_ai.adapters.codex_runtime import (
    APP_SERVER_PROTOCOL,
    CodexAppServerClient,
    CodexProbeState,
    CodexProtocolError,
    CodexRuntimeConfigurationError,
    CodexRuntimeError,
    CodexRuntimeNotFoundError,
    CodexRuntimeProbe,
    CodexRuntimeProcessError,
    CodexRuntimeSettings,
    CodexRuntimeTimeoutError,
    CodexServerInfo,
    CodexThreadPolicy,
    probe_codex_readiness,
    probe_codex_runtime,
)
from odoo_ai.adapters.codex_status import CachedCodexReasoningStatus
from odoo_ai.adapters.context_runtime import load_instance_summary, persist_trace_events
from odoo_ai.adapters.diagnostics_runtime import RuntimeDiagnosticsService
from odoo_ai.adapters.odoo_http import (
    HttpOdooGateway,
    HttpOdooInstanceGateway,
    OdooGatewayError,
    OdooGatewayFactory,
    OdooGatewaySettings,
)
from odoo_ai.adapters.query_tools import (
    ODOO_AGGREGATE_RECORDS,
    ODOO_GET_EFFECTIVE_SCHEMA,
    ODOO_QUERY_RECORDS,
    AggregateRecordsToolData,
    EffectiveSchemaToolData,
    GetEffectiveSchemaRequest,
    QueryRecordsToolData,
    QueryToolBackend,
    QueryToolExecutorFactory,
    build_query_tool_registry,
    query_tool_specs,
)
from odoo_ai.adapters.source_tools import (
    SOURCE_FIND_MODEL_EXTENSIONS,
    SOURCE_FIND_SYMBOL,
    SOURCE_READ_EXCERPT,
    ReadExcerptToolData,
    RuntimeSourceToolBackend,
    SourceToolBackend,
    SourceToolExecutorFactory,
    build_source_tool_registry,
    source_tool_specs,
)

__all__ = [
    "APP_SERVER_PROTOCOL",
    "CodexAppServerClient",
    "CodexAppServerEngine",
    "CodexEngineError",
    "CodexEngineLimits",
    "CodexEngineMetadata",
    "CodexProbeState",
    "CodexProtocolError",
    "CodexRuntimeConfigurationError",
    "CodexRuntimeError",
    "CodexRuntimeNotFoundError",
    "CodexRuntimeProbe",
    "CodexRuntimeProcessError",
    "CodexRuntimeSettings",
    "CodexRuntimeTimeoutError",
    "CachedCodexReasoningStatus",
    "CodexServerInfo",
    "CodexThreadPolicy",
    "HttpOdooGateway",
    "HttpOdooInstanceGateway",
    "OdooGatewayError",
    "OdooGatewayFactory",
    "OdooGatewaySettings",
    "ODOO_AGGREGATE_RECORDS",
    "ODOO_GET_EFFECTIVE_SCHEMA",
    "ODOO_QUERY_RECORDS",
    "AggregateRecordsToolData",
    "EffectiveSchemaToolData",
    "GetEffectiveSchemaRequest",
    "QueryRecordsToolData",
    "QueryToolBackend",
    "QueryToolExecutorFactory",
    "RuntimeDiagnosticsService",
    "RuntimeSourceToolBackend",
    "SOURCE_FIND_MODEL_EXTENSIONS",
    "SOURCE_FIND_SYMBOL",
    "SOURCE_READ_EXCERPT",
    "ReadExcerptToolData",
    "SourceToolBackend",
    "SourceToolExecutorFactory",
    "build_source_tool_registry",
    "build_query_tool_registry",
    "codex_dynamic_tool_name",
    "codex_dynamic_tools",
    "load_instance_summary",
    "persist_trace_events",
    "probe_codex_readiness",
    "probe_codex_runtime",
    "query_tool_specs",
    "serialize_codex_context",
    "source_tool_specs",
]
