"""Replaceable infrastructure adapters for stable service ports."""

from odoo_ai.adapters.action_tools import (
    ODOO_GET_EFFECTIVE_WRITE_SCHEMA,
    ODOO_PREVIEW_BUSINESS_ACTION,
    ODOO_PREVIEW_RECORD_CREATE,
    ODOO_PREVIEW_RECORD_PATCH,
    ActionPreviewToolData,
    ActionToolBackend,
    ActionToolExecutorFactory,
    EffectiveWriteSchemaToolData,
    GetEffectiveWriteSchemaRequest,
    PreviewBusinessActionRequest,
    PreviewRecordCreateRequest,
    PreviewRecordPatchRequest,
    action_tool_specs,
    build_action_tool_registry,
)
from odoo_ai.adapters.codex_engine import (
    CodexAppServerEngine,
    CodexEngineError,
    CodexEngineLimits,
    CodexEngineMetadata,
    codex_dynamic_tool_name,
    codex_dynamic_tools,
    serialize_codex_context,
)
from odoo_ai.adapters.codex_runtime import (
    APP_SERVER_PROTOCOL,
    CodexAppServerClient,
    CodexProbeState,
    CodexProtocolError,
    CodexRuntimeConfigurationError,
    CodexRuntimeError,
    CodexRuntimeNotFoundError,
    CodexRuntimeProbe,
    CodexRuntimeProcessError,
    CodexRuntimeTimeoutError,
    CodexServerInfo,
    CodexThreadPolicy,
    probe_codex_readiness,
    probe_codex_runtime,
)
from odoo_ai.adapters.codex_status import CachedCodexReasoningStatus
from odoo_ai.adapters.configured_codex import (
    ConfiguredCodexRuntimeSettings as CodexRuntimeSettings,
)
from odoo_ai.adapters.configured_diagnostics import (
    ConfiguredRuntimeDiagnosticsService as RuntimeDiagnosticsService,
)
from odoo_ai.adapters.context_runtime import load_instance_summary, persist_trace_events
from odoo_ai.adapters.knowledge_tools import (
    KNOWLEDGE_READ_EXCERPT,
    KNOWLEDGE_SEARCH,
    KnowledgeReadExcerptToolData,
    KnowledgeToolBackend,
    KnowledgeToolExecutorFactory,
    RuntimeKnowledgeToolBackend,
    build_knowledge_tool_registry,
    knowledge_tool_specs,
)
from odoo_ai.adapters.odoo_http import (
    HttpOdooActionGateway,
    HttpOdooGateway,
    HttpOdooInstanceGateway,
    OdooGatewayFactory,
    OdooGatewaySettings,
)
from odoo_ai.adapters.query_tools import (
    ODOO_AGGREGATE_RECORDS,
    ODOO_GET_EFFECTIVE_SCHEMA,
    ODOO_QUERY_RECORDS,
    AggregateRecordsToolData,
    EffectiveSchemaToolData,
    GetEffectiveSchemaRequest,
    QueryRecordsToolData,
    QueryToolBackend,
    QueryToolExecutorFactory,
    build_query_tool_registry,
    query_tool_specs,
)
from odoo_ai.adapters.source_tools import (
    SOURCE_FIND_MODEL_EXTENSIONS,
    SOURCE_FIND_SYMBOL,
    SOURCE_READ_EXCERPT,
    ReadExcerptToolData,
    RuntimeSourceToolBackend,
    SourceToolBackend,
    SourceToolExecutorFactory,
    build_source_tool_registry,
    source_tool_specs,
)
from odoo_ai.ports import OdooGatewayError

__all__ = [
    "APP_SERVER_PROTOCOL",
    "ActionPreviewToolData",
    "ActionToolBackend",
    "ActionToolExecutorFactory",
    "CodexAppServerClient",
    "CodexAppServerEngine",
    "CodexEngineError",
    "CodexEngineLimits",
    "CodexEngineMetadata",
    "CodexProbeState",
    "CodexProtocolError",
    "CodexRuntimeConfigurationError",
    "CodexRuntimeError",
    "CodexRuntimeNotFoundError",
    "CodexRuntimeProbe",
    "CodexRuntimeProcessError",
    "CodexRuntimeSettings",
    "CodexRuntimeTimeoutError",
    "CachedCodexReasoningStatus",
    "CodexServerInfo",
    "CodexThreadPolicy",
    "EffectiveWriteSchemaToolData",
    "HttpOdooGateway",
    "HttpOdooActionGateway",
    "HttpOdooInstanceGateway",
    "GetEffectiveWriteSchemaRequest",
    "KNOWLEDGE_READ_EXCERPT",
    "KNOWLEDGE_SEARCH",
    "KnowledgeReadExcerptToolData",
    "KnowledgeToolBackend",
    "KnowledgeToolExecutorFactory",
    "OdooGatewayError",
    "OdooGatewayFactory",
    "OdooGatewaySettings",
    "ODOO_AGGREGATE_RECORDS",
    "ODOO_GET_EFFECTIVE_SCHEMA",
    "ODOO_GET_EFFECTIVE_WRITE_SCHEMA",
    "ODOO_PREVIEW_BUSINESS_ACTION",
    "ODOO_PREVIEW_RECORD_PATCH",
    "ODOO_PREVIEW_RECORD_CREATE",
    "ODOO_QUERY_RECORDS",
    "AggregateRecordsToolData",
    "EffectiveSchemaToolData",
    "GetEffectiveSchemaRequest",
    "QueryRecordsToolData",
    "QueryToolBackend",
    "QueryToolExecutorFactory",
    "PreviewRecordPatchRequest",
    "PreviewRecordCreateRequest",
    "PreviewBusinessActionRequest",
    "RuntimeDiagnosticsService",
    "RuntimeKnowledgeToolBackend",
    "RuntimeSourceToolBackend",
    "SOURCE_FIND_MODEL_EXTENSIONS",
    "SOURCE_FIND_SYMBOL",
    "SOURCE_READ_EXCERPT",
    "ReadExcerptToolData",
    "SourceToolBackend",
    "SourceToolExecutorFactory",
    "build_source_tool_registry",
    "build_action_tool_registry",
    "build_knowledge_tool_registry",
    "build_query_tool_registry",
    "codex_dynamic_tool_name",
    "codex_dynamic_tools",
    "load_instance_summary",
    "knowledge_tool_specs",
    "persist_trace_events",
    "probe_codex_readiness",
    "probe_codex_runtime",
    "query_tool_specs",
    "action_tool_specs",
    "serialize_codex_context",
    "source_tool_specs",
]
