"""Bounded source discovery, scanning, and static extraction adapters."""

from odoo_ai.source.extractors import (
    ManifestExtractor,
    ParserLimits,
    ProvenanceEvidence,
    PythonAstExtractor,
    SecurityCsvExtractor,
    XmlExtractor,
    classify_module_provenance,
    m3_source_extractors,
)
from odoo_ai.source.scanner import (
    ExtractedSymbol,
    ExtractedXmlRecord,
    FileExtraction,
    FileScanContext,
    ModuleSource,
    NoopExtractor,
    ResolvedSourceRoot,
    RootIssue,
    RootOrigin,
    RootSelection,
    ScanError,
    ScanLimits,
    SourceExtractionError,
    SourceScanMetrics,
    SourceScanner,
    SourceScanResult,
    StoredSourceFile,
    locate_installed_modules,
    resolve_source_roots,
    source_root_overrides_from_env,
)
from odoo_ai.source.sqlalchemy_store import SqlAlchemySourceScanStore

__all__ = [
    "ExtractedSymbol",
    "ExtractedXmlRecord",
    "FileExtraction",
    "FileScanContext",
    "ModuleSource",
    "ManifestExtractor",
    "NoopExtractor",
    "ParserLimits",
    "ProvenanceEvidence",
    "PythonAstExtractor",
    "SecurityCsvExtractor",
    "ResolvedSourceRoot",
    "RootIssue",
    "RootOrigin",
    "RootSelection",
    "ScanError",
    "ScanLimits",
    "SourceScanMetrics",
    "SourceScanResult",
    "SourceScanner",
    "SourceExtractionError",
    "SqlAlchemySourceScanStore",
    "StoredSourceFile",
    "XmlExtractor",
    "classify_module_provenance",
    "locate_installed_modules",
    "m3_source_extractors",
    "resolve_source_roots",
    "source_root_overrides_from_env",
]
